#!/usr/bin/env python3
"""Collect raw filesystem evidence for a single FOCUS path on a given date.

Usage:
    python3 analyze_focus_path.py --path <abs-path> --date YYYY-MM-DD \
        [--nl '<natural language instruction>'] \
        [--max-file-chars 20000] [--max-diff-chars 6000] \
        [--max-files-changed 200] [--max-commits 50]

The script ONLY collects raw evidence. The natural-language summary that lands
in the daily report bullet is generated by the agent invoking the skill, by
reading this output's git.diff_body / file_content / files_changed alongside
the user's nl_instruction. See SKILL.md Step 5d for the bullet-generation
prompt template.

Output schema (stdout, single JSON object):
    {
      "focus_path":     "/abs/path",
      "kind":           "git_dir|fs_dir|file|missing",
      "target_date":    "2026-05-28",
      "nl_instruction": "..." | null,
      "git": {
        "toplevel":      "/abs/repo/root",
        "branch":        "main",
        "commits_today": [{"sha","iso","msg","files":[...]}, ...],
        "diffstat":      "12 files changed, ...",
        "uncommitted":   {"staged":[...], "unstaged":[...], "untracked":[...]},
        "diff_body":     "<truncated unified diff blob>"
      } | null,
      "files_changed":  [{"path","mtime","size"}, ...],
      "file_content":   "<truncated>" | null,
      "is_binary":      false,
      "touched_paths":  ["/abs/...", ...],
      "summary_hint":   "<one-line auto description>",
      "warnings":       ["..."]
    }
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from digest_session import _short  # noqa: E402


EXCLUDE_DIRS = {
    ".git", ".venv", "venv", "node_modules", "__pycache__",
    ".pytest_cache", ".mypy_cache", "dist", "build", ".tox",
    ".idea", ".vscode", "target", ".next", ".cache",
}

MAX_FILE_BYTES = 256 * 1024  # 256 KB hard cap for `kind=file`
FS_DIR_DEPTH_CAP = 4         # walk depth cap for kind=fs_dir
GIT_DIFF_COMMIT_CAP = 10     # max commits to include patches for in diff_body


def _run(cmd: list[str], cwd: str | None = None) -> tuple[int, str, str]:
    try:
        r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=False)
        return r.returncode, r.stdout, r.stderr
    except Exception as e:
        return 127, "", str(e)


def _run_ok(cmd: list[str], cwd: str | None = None) -> str:
    rc, out, _ = _run(cmd, cwd=cwd)
    return out if rc == 0 else ""


def _iso_local(epoch: float) -> str:
    return datetime.fromtimestamp(epoch).astimezone().isoformat(timespec="seconds")


def _day_window(date_str: str) -> tuple[float, float]:
    d = datetime.strptime(date_str, "%Y-%m-%d")
    start = d.replace(hour=0, minute=0, second=0, microsecond=0).astimezone()
    end = d.replace(hour=23, minute=59, second=59, microsecond=999999).astimezone()
    return start.timestamp(), end.timestamp()


def _detect_kind(p: Path) -> str:
    if not p.exists():
        return "missing"
    if p.is_file():
        return "file"
    if p.is_dir():
        rc, _, _ = _run(["git", "-C", str(p), "rev-parse", "--show-toplevel"])
        return "git_dir" if rc == 0 else "fs_dir"
    return "missing"


def _parse_git_log_z(raw: str) -> list[dict]:
    """Parse `git log -z --pretty=format:%H\\x1f%ad\\x1f%s --name-only`."""
    commits: list[dict] = []
    if not raw:
        return commits
    for record in raw.split("\x00\x00"):
        record = record.strip("\x00\n")
        if not record:
            continue
        parts = record.split("\x00")
        header = parts[0]
        files = [f for f in parts[1:] if f]
        try:
            sha, iso, msg = header.split("\x1f", 2)
        except ValueError:
            continue
        commits.append({"sha": sha, "iso": iso, "msg": msg, "files": files})
    return commits


def _parse_porcelain(raw: str) -> tuple[list[str], list[str], list[str]]:
    staged: list[str] = []
    unstaged: list[str] = []
    untracked: list[str] = []
    for line in raw.splitlines():
        if not line:
            continue
        xy, path = line[:2], line[3:]
        if xy == "??":
            untracked.append(path)
            continue
        if xy[0] != " " and xy[0] != "?":
            staged.append(f"{xy[0]}  {path}")
        if xy[1] != " " and xy[1] != "?":
            unstaged.append(f" {xy[1]} {path}")
    return staged, unstaged, untracked


def _is_binary(sample: bytes) -> bool:
    if not sample:
        return False
    nontext = 0
    for b in sample:
        if b < 0x09 or (0x0E <= b < 0x20 and b != 0x1B):
            nontext += 1
    return (nontext / len(sample)) > 0.01


def _collect_git_dir(p: Path, date: str, max_diff_chars: int, max_commits: int,
                     warnings: list[str]) -> tuple[dict, list[str]]:
    repo = str(p)
    toplevel = _run_ok(["git", "-C", repo, "rev-parse", "--show-toplevel"]).strip()
    branch = _run_ok(["git", "-C", repo, "rev-parse", "--abbrev-ref", "HEAD"]).strip()

    since = f"{date} 00:00:00"
    until = f"{date} 23:59:59"
    log_raw = _run_ok([
        "git", "-C", repo, "log",
        f"--since={since}", f"--until={until}",
        "--no-merges",
        f"--max-count={max_commits}",
        "--date=iso-strict",
        "--pretty=format:%H%x1f%ad%x1f%s",
        "--name-only", "-z",
    ])
    commits = _parse_git_log_z(log_raw)

    diffstat = ""
    if commits:
        # git log is newest-first: commits[0]=newest, commits[-1]=oldest
        oldest_sha = commits[-1]["sha"]
        newest_sha = commits[0]["sha"]
        rc, out, _ = _run([
            "git", "-C", repo, "diff", "--shortstat",
            f"{oldest_sha}^..{newest_sha}",
        ])
        diffstat = (out or "").strip()

    porcelain = _run_ok(["git", "-C", repo, "status", "--porcelain=v1", "-uall"])
    staged, unstaged, untracked = _parse_porcelain(porcelain)

    # diff_body: uncommitted first (most actionable), then today's commits
    chunks: list[str] = []
    unstaged_diff = _run_ok(["git", "-C", repo, "diff"])
    if unstaged_diff.strip():
        chunks.append("=== git diff (unstaged) ===\n" + unstaged_diff)
    staged_diff = _run_ok(["git", "-C", repo, "diff", "--cached"])
    if staged_diff.strip():
        chunks.append("=== git diff --cached (staged) ===\n" + staged_diff)
    for c in commits[:GIT_DIFF_COMMIT_CAP]:
        body = _run_ok(["git", "-C", repo, "show", "--stat", "--patch", c["sha"]])
        if body.strip():
            chunks.append(f"=== commit {c['sha'][:8]} {c['msg']} ===\n{body}")
    if len(commits) > GIT_DIFF_COMMIT_CAP:
        warnings.append(
            f"diff_body kept patches for first {GIT_DIFF_COMMIT_CAP}/{len(commits)} commits"
        )
    diff_body = _short("\n\n".join(chunks), max_diff_chars)

    touched: set[str] = {toplevel}
    for c in commits:
        for f in c["files"]:
            touched.add(str(Path(toplevel) / f))
    for path in [s[3:].strip() for s in staged] + \
                [s[3:].strip() for s in unstaged] + untracked:
        if path:
            touched.add(str(Path(toplevel) / path))

    return {
        "toplevel": toplevel,
        "branch": branch,
        "commits_today": commits,
        "diffstat": diffstat,
        "uncommitted": {"staged": staged, "unstaged": unstaged, "untracked": untracked},
        "diff_body": diff_body,
    }, sorted(touched)


def _collect_fs_dir(p: Path, date: str, max_files: int,
                    warnings: list[str]) -> tuple[list[dict], list[str]]:
    start_ts, end_ts = _day_window(date)
    changed: list[dict] = []
    base_depth = str(p).count(os.sep)

    for root, dirs, files in os.walk(str(p), topdown=True):
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS and not d.startswith(".")]
        if root.count(os.sep) - base_depth > FS_DIR_DEPTH_CAP:
            dirs[:] = []
            continue
        for fn in files:
            if fn.startswith("."):
                continue
            fp = Path(root) / fn
            try:
                st = fp.stat()
            except OSError:
                continue
            if start_ts <= st.st_mtime <= end_ts:
                changed.append({
                    "path": str(fp),
                    "mtime": _iso_local(st.st_mtime),
                    "size": st.st_size,
                })
                if len(changed) >= max_files:
                    warnings.append(
                        f"hit max_files_changed={max_files}, list truncated"
                    )
                    break
        if len(changed) >= max_files:
            break

    touched = [str(p)] + [c["path"] for c in changed]
    return changed, touched


def _collect_file(p: Path, max_chars: int, warnings: list[str]) -> tuple[str | None, bool]:
    size = p.stat().st_size
    if size > MAX_FILE_BYTES:
        warnings.append(f"file {size} bytes > {MAX_FILE_BYTES}, content skipped")
        return None, False
    try:
        raw = p.read_bytes()
    except OSError as e:
        warnings.append(f"read failed: {e}")
        return None, False
    sample = raw[:8192]
    if _is_binary(sample):
        return None, True
    text = raw.decode("utf-8", errors="replace")
    return _short(text, max_chars), False


def analyze(focus_path: Path, target_date: str, nl_instruction: str | None,
            max_file_chars: int, max_diff_chars: int,
            max_files_changed: int, max_commits: int) -> dict:
    warnings: list[str] = []
    kind = _detect_kind(focus_path)

    out: dict = {
        "focus_path": str(focus_path),
        "kind": kind,
        "target_date": target_date,
        "nl_instruction": nl_instruction,
        "git": None,
        "files_changed": [],
        "file_content": None,
        "is_binary": False,
        "touched_paths": [],
        "summary_hint": "",
        "warnings": warnings,
    }

    if kind == "missing":
        out["summary_hint"] = f"missing: {focus_path}"
        return out

    if kind == "git_dir":
        git, touched = _collect_git_dir(
            focus_path, target_date, max_diff_chars, max_commits, warnings,
        )
        out["git"] = git
        out["touched_paths"] = touched
        n_commits = len(git["commits_today"])
        n_unc = (len(git["uncommitted"]["staged"])
                 + len(git["uncommitted"]["unstaged"])
                 + len(git["uncommitted"]["untracked"]))
        out["summary_hint"] = (
            f"git_dir {focus_path} ({git['branch']}): "
            f"{n_commits} commit(s) on {target_date}, {n_unc} uncommitted change(s)"
        )
        return out

    if kind == "fs_dir":
        changed, touched = _collect_fs_dir(
            focus_path, target_date, max_files_changed, warnings,
        )
        out["files_changed"] = changed
        out["touched_paths"] = touched
        out["summary_hint"] = (
            f"fs_dir {focus_path}: {len(changed)} file(s) changed on {target_date}"
        )
        return out

    # kind == "file"
    content, is_binary = _collect_file(focus_path, max_file_chars, warnings)
    out["file_content"] = content
    out["is_binary"] = is_binary
    out["touched_paths"] = [str(focus_path)]
    size = focus_path.stat().st_size
    out["summary_hint"] = (
        f"file {focus_path.name} ({size} bytes"
        f"{', binary' if is_binary else ''})"
    )
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--path", required=True, type=Path)
    p.add_argument("--date", required=True, help="YYYY-MM-DD (local tz)")
    p.add_argument("--nl", default=None)
    p.add_argument("--max-file-chars", type=int, default=20000)
    p.add_argument("--max-diff-chars", type=int, default=6000)
    p.add_argument("--max-files-changed", type=int, default=200)
    p.add_argument("--max-commits", type=int, default=50)
    args = p.parse_args()

    result = analyze(
        focus_path=args.path,
        target_date=args.date,
        nl_instruction=args.nl,
        max_file_chars=args.max_file_chars,
        max_diff_chars=args.max_diff_chars,
        max_files_changed=args.max_files_changed,
        max_commits=args.max_commits,
    )
    json.dump(result, sys.stdout, ensure_ascii=False, indent=2)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
